// Generated by CoffeeScript 1.6.3
(function() {
  var run;

  run = require('../index.js');

  run.run({
    text: "console.log(123);throw new Error('An error occurred');"
  }, function(e, o) {
    return console.log(o.log);
  });

  run.runCMD({
    cmd: "ls",
    parameter: ['..'],
    log: function(data) {
      return console.log(data + '');
    }
  }, function(e, o) {
    return console.log(o);
  });

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
