// Generated by CoffeeScript 1.12.7
(function() {
  var assert, fs, run;

  run = require('../index.js');

  fs = require('fs');

  assert = require('assert');

  describe("test methods", function() {
    it("should be able to run string scripts", function(done) {
      return run.run({
        text: fs.readFileSync("test/testapp.txt").toString()
      }, function(e, o) {
        console.log(o.log);
        assert.equal(o.log.includes("Error: An error occurred"), 1);
        return done(null);
      });
    });
    return it("should be able to run cmd", function(done) {
      return run.runCMD({
        cmd: "ls",
        parameter: ['..'],
        log: function(data) {
          return console.log(data + '');
        }
      }, function(e, o) {
        console.log(o);
        return done(e);
      });
    });
  });

}).call(this);
