// Generated by CoffeeScript 1.6.3
(function() {
  var run;

  run = require('../index.js');

  run.run({
    script: "console.log(123);console.log(123);console.log(123);console.log(123/0);throw new Error('An error occurred');"
  }, function(e, o) {
    return console.log(o.log);
  });

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
