// Generated by CoffeeScript 1.6.3
(function() {
  var vm, _;

  vm = require("vm");

  _ = require('lodash');

  exports.run = function(o, cb) {
    var Log, context, e, err, log;
    o = o || {};
    o.options = o.options || {};
    o.options.displayErrors = false;
    Log = "";
    log = function(obj) {
      if (obj) {
        if (typeof obj === "string") {
          return Log += '\n' + obj;
        } else if (typeof obj === "object") {
          return Log += '\n' + JSON.stringify(obj, null, 2);
        } else {
          return Log += '\n' + obj + '';
        }
      }
    };
    o.script = o.script || "";
    o.context = o.context || {};
    context = {
      log: log,
      console: {
        log: log
      },
      process: {
        stdout: {
          write: log
        },
        stderr: {
          write: log
        }
      }
    };
    o.context = _.extend(context, o.context);
    err = null;
    try {
      vm.runInNewContext(o.script, o.context, o.options);
    } catch (_error) {
      e = _error;
      log(JSON.stringify(e.stack, null, 2));
      err = e;
    }
    o.log = Log;
    return cb(err, o);
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
